apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonAnnotations:
  app: mykustom-annontations

namePrefix: kustom-

nameSuffix: -v1

labels:
  - includeSelectors: true
    pairs:
      app: kustomwebapp
