apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - path: replicas.yaml
  - path: spec.yaml

configMapGenerator:
  - envs:
      - config.properties
    name: mykustom-map
