# don't think this is working atm - need to look into if it's going to be worthwhile putting all kustomize patching in one single file as it won't get messed with deployment to deployment anyhow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  template:
    spec:   # Pod spec
        ports:
          - containerPort: 90
