# don't think this is working atm - need to look into if it's going to be worthwhile putting all kustomize patching in one single file as it won't get messed with deployment to deployment anyhow
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  ports:
    - port: 90
      protocol: TCP
      name: flask