apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-webapp-prod
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-webapp
    repoURL: 'https://github.com/JamieM9422/argo-examples.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
