apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: helm-apps
spec:
  generators:
    - git:
        directories: 
          - path: helm-environments/*
        repoURL: "https://github.com/JamieM9422/argo-examples.git"
        revision: HEAD #just means the latest commit
  template: 
    metadata: 
      name: "helm-webapp-{{path.basename}}" #this gets the lowest dir's in the path
      labels:
        managedBy: argocd-application-set
    spec: 
      destination:
        namespace: "{{path.basename}}"
        server: "https://kubernetes.default.svc"
      project: default
      source: 
        path: "helm-webapp-982"
        repoURL: "https://github.com/JamieM9422/argo-examples.git"
        targetRevision: HEAD
        helm:
          valueFiles:
            - "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
 